# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 00:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 19, 0, 22, 5, 889212, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.ImageField(upload_to='myblog-user-message-photos'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 19, 0, 22, 5, 888072, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
