# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 23:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 23, 3, 39, 264414, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='picture',
            field=models.ImageField(upload_to='myblog-user-message-photos'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 18, 23, 3, 39, 263260, tzinfo=utc)),
        ),
    ]
